note book for the kaggle hackaton challenge 

In [2]:
import pandas as pd               #For data loading and data manipulation
import seaborn as sns             #For data visualization 
import matplotlib.pyplot as plt   #For data visualization
%matplotlib inline
import re

import nltk
from nltk.corpus import stopwords #For stopword removals

import string                     #For Punctuations

import numpy as np


In [3]:
# Display.max_colwidth option  set to None to show all text content without truncation
pd.set_option('display.max_colwidth', None)

# Your code to read the DataFrame
train_df = pd.read_csv('train_set.csv')
test_df = pd.read_csv('test_set.csv')


In [4]:
train_df.head(10)

lang_id  \
0     xho   
1     xho   
2     eng   
3     nso   
4     ven   
5     nso   
6     tsn   
7     ven   
8     nso   
9     tsn   

                                                                                                                                                                                                                                                                                                          text  
0                                                                                 umgaqo-siseko wenza amalungiselelo kumaziko axhasa ulawulo lwesininzi kunye nokuthath inxaxheba kwabafazi ezi ziquka phakathi kwezinye zazo ikomishoni yokulingana ngokwesini ikomishoni yamalungelo oluntu lomzantsi afrika  
1                                                 i-dha iya kuba nobulumko bokubeka umsebenzi naphi na kwisebe ngokusekwe kwiimfuno zokusebenza zalo emva kokubonana nomsebenzi kunye okanye imanyano yakhe ukuba ulandulo lomntu onjalo alufanelekanga i-dha mayibize uncedo olufanelekileyo elungelweni layo  
2                                     the province of kwazulu-natal department of transport invites tenders from established contractors experienced in bridge construction for the construction of the kwajolwayo tugela river pedestrian bridge near tugela ferry the duration of the project will be months  
3                                                                                    o netefatša gore o ba file dilo ka moka tše le dumelelanego ka tšona mohlala maleri a magolo a a šomišwago go fihlelela meagong e metelele scaffolds a a bolokegilego lefelo la maleba la go šomela go phela gabotse bjbj  
4                                                              khomishini ya ndinganyiso ya mbeu yo ewa maana u ya nga mulayo wa khomishini ya ndinganyiso ya mbeu u thetshelesa mbilaelo dzine dza tshimbilelana na tshialula u ya nga mbeu nahone i ivhea sa foramu ya thungo u ya nga mulayo wa ndinganyiso  
5                                                                                       dinyakišišo tše tša go dirwa gabedi ka ngwaga di tla lebelela diphetogo tša mebaraka ya mešomo le mekgwa ga mmogo le go thapiwa mešomong ka makaleng ao mešomo ao lego molaong le ao a sego molaong le go hloka me omo  
6  kgetse nngwe le nngwe e e sa faposiwang mo tshekong go ya ka temana ya a e tshwanetse kwa ntle ga fa kgetse e tsholotswe kgotsa e fetiseditswe kwa kgotlatshekelo ya bana ya fetisediwa kwa kgotlatshekelo ya bosiamisi ya ngwana gore a ikarabele mo tatofatsong le go sekiwa ga kgetse go ya ka kgaolo ya  
7                                            mbadelo dze dza laelwa dzi do kwama mahatulele apo a khothe ya madzhisitirata lihoro line la si vhe na mulandu li do vha lone line la wana masheleni ngeno lihoro le la wanwa mulandu li tshi do vha lone line la tea u lifha ayo masheleni o laelwaho nga khothe  
8             maloko a dikhuduthamaga a ikarabela mongwe le mongwe go tonakgolo le go thteramelao ya profense malebana le taolo ya dipotfolio tša bona mme maloko a mangwe ka moka a khuduthamaga le wona bjalo a ikrabela ka seboka mabapi le phethagatšo ya mediro ya mmušo wa profense le go merero ya wona  
9                                                                                         fa le dirisiwa lebone le tshwanetse go bontsha lesedi le le benyabenyang le le bogale jo bo dirang gore le kgone go bonwa ke motho yo o bonang sentle mo leseding le le tlwaelegileng mo sekgaleng sa dimitara di le

In [6]:
train_df.shape

(33000, 2)

In [7]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33000 entries, 0 to 32999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   lang_id  33000 non-null  object
 1   text     33000 non-null  object
dtypes: object(2)
memory usage: 515.8+ KB


In [9]:
df_train = train_df.copy() #Let us make a copy of our dataframe to avoid modifying the original dataframe

In [12]:
#To get a list of english stopwords
stop_words = stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [14]:
clean_texts = []

for text in df_train['text']:
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    clean_text = ' '.join(filtered_words)
    clean_texts.append(clean_text)

# clean_texts
df_train['clean_text'] = clean_texts
df_train.head()

lang_id  \
0     xho   
1     xho   
2     eng   
3     nso   
4     ven   

                                                                                                                                                                                                                                                                       text  \
0                                              umgaqo-siseko wenza amalungiselelo kumaziko axhasa ulawulo lwesininzi kunye nokuthath inxaxheba kwabafazi ezi ziquka phakathi kwezinye zazo ikomishoni yokulingana ngokwesini ikomishoni yamalungelo oluntu lomzantsi afrika   
1              i-dha iya kuba nobulumko bokubeka umsebenzi naphi na kwisebe ngokusekwe kwiimfuno zokusebenza zalo emva kokubonana nomsebenzi kunye okanye imanyano yakhe ukuba ulandulo lomntu onjalo alufanelekanga i-dha mayibize uncedo olufanelekileyo elungelweni layo   
2  the province of kwazulu-natal department of transport invites tenders from established contractors experienced in bridge construction for the construction of the kwajolwayo tugela river pedestrian bridge near tugela ferry the duration of the project will be months   
3                                                 o netefatša gore o ba file dilo ka moka tše le dumelelanego ka tšona mohlala maleri a magolo a a šomišwago go fihlelela meagong e metelele scaffolds a a bolokegilego lefelo la maleba la go šomela go phela gabotse bjbj   
4                           khomishini ya ndinganyiso ya mbeu yo ewa maana u ya nga mulayo wa khomishini ya ndinganyiso ya mbeu u thetshelesa mbilaelo dzine dza tshimbilelana na tshialula u ya nga mbeu nahone i ivhea sa foramu ya thungo u ya nga mulayo wa ndinganyiso   

                                                                                                                                                                                                                                                     clean_text  
0                                  umgaqo-siseko wenza amalungiselelo kumaziko axhasa ulawulo lwesininzi kunye nokuthath inxaxheba kwabafazi ezi ziquka phakathi kwezinye zazo ikomishoni yokulingana ngokwesini ikomishoni yamalungelo oluntu lomzantsi afrika  
1  i-dha iya kuba nobulumko bokubeka umsebenzi naphi na kwisebe ngokusekwe kwiimfuno zokusebenza zalo emva kokubonana nomsebenzi kunye okanye imanyano yakhe ukuba ulandulo lomntu onjalo alufanelekanga i-dha mayibize uncedo olufanelekileyo elungelweni layo  
2                                          province kwazulu-natal department transport invites tenders established contractors experienced bridge construction construction kwajolwayo tugela river pedestrian bridge near tugela ferry duration project months  
3                                                   netefatša gore ba file dilo ka moka tše le dumelelanego ka tšona mohlala maleri magolo šomišwago go fihlelela meagong e metelele scaffolds bolokegilego lefelo la maleba la go šomela go phela gabotse bjbj  
4                 khomishini ya ndinganyiso ya mbeu yo ewa maana u ya nga mulayo wa khomishini ya ndinganyiso ya mbeu u thetshelesa mbilaelo dzine dza tshimbilelana na tshialula u ya nga mbeu nahone ivhea sa foramu ya thungo u ya nga mulayo wa ndinganyiso

In [16]:
#Convert message to lower case
df_train['clean_text'] = df_train['clean_text'].str.lower()

print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [24]:
def remove_punctuation(text):
    return ''.join([l for l in text if l not in string.punctuation])


df_train['clean_text'] = df_train['clean_text'].apply(remove_punctuation)
df_train['clean_text'].iloc[9]

'fa le dirisiwa lebone le tshwanetse go bontsha lesedi le le benyabenyang le le bogale jo bo dirang gore le kgone go bonwa ke motho yo bonang sentle mo leseding le le tlwaelegileng mo sekgaleng sa dimitara di le'

In [25]:
df_train.head()

lang_id  \
0     xho   
1     xho   
2     eng   
3     nso   
4     ven   

                                                                                                                                                                                                                                                                       text  \
0                                              umgaqo-siseko wenza amalungiselelo kumaziko axhasa ulawulo lwesininzi kunye nokuthath inxaxheba kwabafazi ezi ziquka phakathi kwezinye zazo ikomishoni yokulingana ngokwesini ikomishoni yamalungelo oluntu lomzantsi afrika   
1              i-dha iya kuba nobulumko bokubeka umsebenzi naphi na kwisebe ngokusekwe kwiimfuno zokusebenza zalo emva kokubonana nomsebenzi kunye okanye imanyano yakhe ukuba ulandulo lomntu onjalo alufanelekanga i-dha mayibize uncedo olufanelekileyo elungelweni layo   
2  the province of kwazulu-natal department of transport invites tenders from established contractors experienced in bridge construction for the construction of the kwajolwayo tugela river pedestrian bridge near tugela ferry the duration of the project will be months   
3                                                 o netefatša gore o ba file dilo ka moka tše le dumelelanego ka tšona mohlala maleri a magolo a a šomišwago go fihlelela meagong e metelele scaffolds a a bolokegilego lefelo la maleba la go šomela go phela gabotse bjbj   
4                           khomishini ya ndinganyiso ya mbeu yo ewa maana u ya nga mulayo wa khomishini ya ndinganyiso ya mbeu u thetshelesa mbilaelo dzine dza tshimbilelana na tshialula u ya nga mbeu nahone i ivhea sa foramu ya thungo u ya nga mulayo wa ndinganyiso   

                                                                                                                                                                                                                                                   clean_text  
0                                 umgaqosiseko wenza amalungiselelo kumaziko axhasa ulawulo lwesininzi kunye nokuthath inxaxheba kwabafazi ezi ziquka phakathi kwezinye zazo ikomishoni yokulingana ngokwesini ikomishoni yamalungelo oluntu lomzantsi afrika  
1  idha iya kuba nobulumko bokubeka umsebenzi naphi na kwisebe ngokusekwe kwiimfuno zokusebenza zalo emva kokubonana nomsebenzi kunye okanye imanyano yakhe ukuba ulandulo lomntu onjalo alufanelekanga idha mayibize uncedo olufanelekileyo elungelweni layo  
2                                         province kwazulunatal department transport invites tenders established contractors experienced bridge construction construction kwajolwayo tugela river pedestrian bridge near tugela ferry duration project months  
3                                                 netefatša gore ba file dilo ka moka tše le dumelelanego ka tšona mohlala maleri magolo šomišwago go fihlelela meagong e metelele scaffolds bolokegilego lefelo la maleba la go šomela go phela gabotse bjbj  
4               khomishini ya ndinganyiso ya mbeu yo ewa maana u ya nga mulayo wa khomishini ya ndinganyiso ya mbeu u thetshelesa mbilaelo dzine dza tshimbilelana na tshialula u ya nga mbeu nahone ivhea sa foramu ya thungo u ya nga mulayo wa ndinganyiso

## count vectorizer

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
vect = CountVectorizer()
vect.fit(df_train['clean_text'])

CountVectorizer()

In [28]:
vect = CountVectorizer()

In [29]:
vect = CountVectorizer(ngram_range=(1, 2))

In [30]:
vect = CountVectorizer(max_df=0.5)

In [31]:
vect = CountVectorizer(min_df=2)

In [32]:
betterVect = CountVectorizer( min_df=2, 
                             max_df=0.5, 
                             ngram_range=(1, 1))

In [33]:
df_new=betterVect.fit_transform(df_train['clean_text'])

In [34]:
betterVect

CountVectorizer(max_df=0.5, min_df=2)

In [95]:
df_new

<33000x11 sparse matrix of type '<class 'numpy.int64'>'
	with 33000 stored elements in Compressed Sparse Row format>

In [36]:
df 

  (0, 56040)	1
  (0, 59992)	1
  (0, 1882)	1
  (0, 24043)	1
  (0, 3339)	1
  (0, 55818)	1
  (0, 32018)	1
  (0, 24581)	1
  (0, 41066)	1
  (0, 19478)	1
  (0, 25353)	1
  (0, 13717)	1
  (0, 63583)	1
  (0, 44333)	1
  (0, 26553)	1
  (0, 63094)	1
  (0, 18122)	2
  (0, 62626)	1
  (0, 39812)	1
  (0, 61243)	1
  (0, 42799)	1
  (0, 31222)	1
  (0, 1065)	1
  (1, 24581)	1
  (1, 17495)	2
  :	:
  (32998, 42192)	1
  (32998, 12091)	1
  (32999, 27655)	1
  (32999, 61085)	1
  (32999, 59104)	1
  (32999, 33640)	1
  (32999, 21388)	1
  (32999, 16891)	3
  (32999, 53252)	3
  (32999, 27539)	1
  (32999, 12435)	1
  (32999, 9119)	1
  (32999, 32291)	1
  (32999, 30511)	2
  (32999, 13347)	1
  (32999, 22743)	1
  (32999, 27936)	1
  (32999, 32717)	1
  (32999, 42977)	2
  (32999, 8733)	1
  (32999, 62506)	1
  (32999, 51942)	1
  (32999, 16557)	1
  (32999, 37200)	1
  (32999, 9281)	1


In [38]:
train_df["lang_id"].values

array(['xho', 'xho', 'eng', ..., 'eng', 'xho', 'sot'], dtype=object)

In [60]:
y=df_train['lang_id']
y

0        xho
1        xho
2        eng
3        nso
4        ven
        ... 
32995    tsn
32996    sot
32997    eng
32998    xho
32999    sot
Name: lang_id, Length: 33000, dtype: object

In [61]:
X_train=df_train['clean_text']
X_train

0                                                                       umgaqosiseko wenza amalungiselelo kumaziko axhasa ulawulo lwesininzi kunye nokuthath inxaxheba kwabafazi ezi ziquka phakathi kwezinye zazo ikomishoni yokulingana ngokwesini ikomishoni yamalungelo oluntu lomzantsi afrika
1                                        idha iya kuba nobulumko bokubeka umsebenzi naphi na kwisebe ngokusekwe kwiimfuno zokusebenza zalo emva kokubonana nomsebenzi kunye okanye imanyano yakhe ukuba ulandulo lomntu onjalo alufanelekanga idha mayibize uncedo olufanelekileyo elungelweni layo
2                                                                               province kwazulunatal department transport invites tenders established contractors experienced bridge construction construction kwajolwayo tugela river pedestrian bridge near tugela ferry duration project months
3                                                                                       netefatša gore ba file dilo ka moka 

In [62]:
from sklearn.model_selection import train_test_split

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X_train,y, test_size=0.2, random_state=42)

In [65]:
len(X_train)

26400

In [66]:
len(X_test)

6600

In [75]:
len(y_train)

26400

## pipeline

In [76]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

lang_clf =Pipeline([('tfidf',TfidfVectorizer()),('clf',LinearSVC())])
lang_clf.fit(X_train,y_train)
y_pred = lang_clf.predict(X_test)

print("The accuracy score of the SVC is:", accuracy_score(y_test, y_pred))
print("\n\nClassification Report:\n\n", classification_report(y_test, y_pred))

The accuracy score of the SVC is: 0.9974242424242424


Classification Report:

               precision    recall  f1-score   support

         afr       1.00      1.00      1.00       583
         eng       1.00      1.00      1.00       615
         nbl       0.99      0.99      0.99       583
         nso       1.00      1.00      1.00       625
         sot       1.00      1.00      1.00       618
         ssw       1.00      1.00      1.00       584
         tsn       1.00      1.00      1.00       598
         tso       1.00      1.00      1.00       561
         ven       1.00      1.00      1.00       634
         xho       0.99      1.00      1.00       609
         zul       0.99      0.99      0.99       590

    accuracy                           1.00      6600
   macro avg       1.00      1.00      1.00      6600
weighted avg       1.00      1.00      1.00      6600



In [77]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [78]:
print(confusion_matrix(y_test,y_pred))

[[583   0   0   0   0   0   0   0   0   0   0]
 [  0 615   0   0   0   0   0   0   0   0   0]
 [  0   1 579   0   0   0   0   0   0   1   2]
 [  0   0   0 623   1   0   1   0   0   0   0]
 [  0   0   0   0 618   0   0   0   0   0   0]
 [  0   0   0   0   0 583   0   0   0   0   1]
 [  1   0   0   0   1   0 596   0   0   0   0]
 [  0   0   0   0   0   0   0 561   0   0   0]
 [  0   0   0   0   0   0   0   0 634   0   0]
 [  0   0   1   0   0   0   0   0   0 607   1]
 [  0   0   3   0   0   0   0   0   0   3 584]]


In [81]:
from sklearn.linear_model import LogisticRegression

In [82]:
lr = LogisticRegression(max_iter=1000)

In [83]:
result=lang_clf.predict(X_test)

In [85]:
DAF=pd.DataFrame(result,columns=["lang_id"])
DAF.head()

lang_id
0     sot
1     nso
2     eng
3     nso
4     nso

In [86]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, result)
print("Accuracy:", accuracy)

Accuracy: 0.9974242424242424


In [87]:
output=pd.DataFrame({"index":test_df["index"]})
submission=output.join(DAF)
submission

index lang_id
0         1     sot
1         2     nso
2         3     eng
3         4     nso
4         5     nso
...     ...     ...
5677   5678     zul
5678   5679     tso
5679   5680     zul
5680   5681     sot
5681   5682     eng

[5682 rows x 2 columns]

In [88]:
submission.to_csv("submissions.csv",index=False)

In [93]:
df_newer=betterVect.fit_transform(df_train['lang_id'])

In [94]:
df_newer["lang_id"].values

IndexError: Index dimension must be 1 or 2

In [90]:
from sklearn.preprocessing import StandardScaler

# Scale the tweet vectors
scaler = StandardScaler(with_mean=False)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_TEST_scaled= scaler.transform(X_TEST)

ValueError: could not convert string to float: 'tshedimošo ka ga mokgwa wo ka wona diinstitšušene tša setšhaba le tša poraebete di ka hlamago dimanyuale ka wona le ka mokgwa wo ka wona bakgopedi ba ka fihlelelago direkoto ka wona ga mmogo le go ntšhetšha pepeneneng ka maithaopo ga direkoto tša magoro mangwe'

In [89]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
# Initialize Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100)

# Train the classifier
rf_classifier.fit(X_train_scaled, y_train)

# Make predictions on the testing data
y_pred = rf_classifier.predict(X_test_scaled)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Random Forest Accuracy:", accuracy)

NameError: name 'X_train_scaled' is not defined